[build]
command = "./.cloudflare/build-command.sh"
output_directory = "dist"
base_directory = ""

[build.environment]
NODE_VERSION = "18"

[site]
bucket = "./dist"
entry-point = "./.cloudflare/workers-site"

[routes]
"/*" = { worker = false }
"/api/*" = { worker = true }

[env.production]
VITE_API_URL = "https://tryvr.pages.dev/api"

[env.development]
VITE_API_URL = "http://localhost:8788/api" 