name = "tryvr"
compatibility_date = "2023-01-01"

# Pages configuration
pages_build_output_dir = "dist"

# Environment variables
[vars]
API_KEY = "your-api-key"
DEBUG = "false"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "tryvr"
database_id = "1e9a1ae1-42dc-41da-ae5e-6c4f4daff98e"

# R2 Storage configuration
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "tryvr"
preview_bucket_name = "tryvr-preview"

# Routes
routes = [
  { pattern = "/*", worker = false },
  { pattern = "/api/*", worker = true }
]

# Environment-specific configurations
[env.production]
routes = [
  { pattern = "/api/*", script = "api" }
]

[[env.production.d1_databases]]
binding = "DB"
database_name = "tryvr-db"
database_id = "placeholder-id"

[env.preview]
routes = [
  { pattern = "/api/*", script = "api" }
]

[[env.preview.d1_databases]]
binding = "DB"
database_name = "tryvr-db-dev"
database_id = "placeholder-id" 